# Page settings

baseURL = "https://pratikstar.github.io//"
languageCode = "en"
title = "Pratik Sutar's Resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"


[params]
    author = "PratikStar"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Pratik Sutar"
        tagline = "Full-stack Software Engineer"
        avatar = "avatar.png"


    [params.summary]
        enable = true
        text = "TODO. Summarise your career here. What will go here? purpose of professional life. Ambitions."


    [params.contact]
        enable = true
        location = "Tokyo, Japan"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "070 4304 2123"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "sutarpratik2012@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "pratikstar.github.io"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BTech in Computer Science"
        university = "VJTI, Mumbai"
        dates = "2012 - 2016"


    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Junction Tokyo 2018"
        body = "First runner-up"
        date = "2018"
        [[params.awards.list]]
        name = "Deep learning Rakuten"
        body = "Winner in ECID department"
        date = "2017"
        [[params.awards.list]]
        name = "Barclays Hackathon"
        body = "First runner-up"
        date = "2015"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Java/Python/PHP"
        [[params.skills.list.items]]
        details = "JavaScript/React/Node.js"
        [[params.skills.list.items]]
        details = "MySQL/Redis/Elasticsearch"
        [[params.skills.list.items]]
        details = "Docker/Kubernetes/Jenkins"
        [[params.skills.list.items]]
        details = "Kafka/RabbitMQ/Consul"
        [[params.skills.list.items]]
        details = "Software Architecture"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective Communicator"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Hindi"
        level = "Native"
        [[params.languages.list]]
        name = "Japanese"
        level = "Beginner"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Guitar & Flute"
        [[params.interests.list]]
        name = "Sport Programming"
        [[params.interests.list]]
        name = "Cycling"
        [[params.interests.list]]
        name = "Badminton"
        [[params.interests.list]]
        name = "Cooking"


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Rakuten, Inc."
        dates = "Oct' 2016 - Present"
        company = "Full Stack Developer & Tech lead"
        details = "Working as a tech-lead in the 'Bookmark' service in Rakuten platform. Led projects having user base in millions and dealt with conerns on design and scalability. Responsible for techinal growth of the service as well as working to improve the development process."
        [[params.experience.list.items]]
        details = "Technical-lead - Project planning, assignment and execution."
        [[params.experience.list.items]]
        details = "System Architect - Architecture for Bookmark service. Addressing Scalability, Reliability and Performance"
        [[params.experience.list.items]]
        details = "Bookmark Search - Designed & implemented Search feature on the Bookmark to be used by million of users in Japan."
        [[params.experience.list.items]]
        details = "Containerization - Initiated the shift to containerization and micro-services architecture."
        [[params.experience.list.items]]
        details = "Mentor-ship - Coached more than 4 newly joined engineers. Currently leading a team of 5"

        [[params.experience.list]]
        title = "Credit Suisse Business Analytics, India"
        dates = "June 2015 - July 2015 & July 2016 - Sept 2016"
        [[params.experience.list.items]]
        details = "Built Searching and Indexing tool based on Elasticsearch for the COO office."
        [[params.experience.list.items]]
        details = "Worked on customer transaction big-data on Apache Hadoop and Hive"

        [[params.experience.list]]
        title = "Citrus Payment Solutions Pvt. Ltd."
        dates = "December 2015 - March 2016"
        company = "Data Analyst & Developer"
        [[params.experience.list.items]]
        details = "Worked on Apache Storm as real-time distributed computation layer for analysis on user payment data."

        [[params.experience.list]]
        title = "Catalyst Labs Pvt. Ltd."
        dates = "Jan 2015 - April 2015"
        company = "Android Developer"
        [[params.experience.list.items]]
        details = "Created a Location aware Android app with geocoding. Integrated Aadhaar card(Indian National UID) support."

        [[params.experience.list]]
        title = "Cubez Technocrats Pvt. Ltd."
        dates = "Dec 2014 - Jan 2015"
        company = "Android & Embedded Systems Developer"
        [[params.experience.list.items]]
        details = "Experienced with Micro-controller, ATmega-16, using Atmel Studio for it’s programming"


        [[params.experience.list]]
        title = "Shanket Classes Pvt. Ltd."
        dates = "Feb 2014 - Feb 2016"
        company = "Lecturer in Physics"
        [[params.experience.list.items]]
        details = "Taught theoretical and applied Physics & Electronics to high school students."
        [[params.experience.list.items]]
        details = "Improved teaching skills with batches of 50+ students at times"


    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Gifty"
        tagline = "A personalised recommendation system based on user’s interests drawn from social media activity"

        [[params.projects.list]]
        title = "UberPack"
        tagline = "A location aware bag-pack with remote tracker for students. Built an Android app for monitoring"

        [[params.projects.list]]
        title = "EasyWay"
        tagline = "An e-KYC system concept for Barclays with extension for bio-metric and integration with user UUID"

        [[params.projects.list]]
        title = "Frenbuy"
        tagline = "Online high-trust classifieds platform for people within network. Built in Android App"


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/PratikStar"
        title = "PratikStar"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/pratiksutar/"
        title = "Pratik Sutar"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/PratikStar"
        title = "@PratikStar"
